# S3 initializes py_s3 only when connect is called

    Code
      print(s3)
    Output
      S3:
        tmproot: . 
        bucket: NULL 
        prefix: NULL 
        s3root: NULL 
        connected: FALSE 

---

    Code
      s3$connect()
    Condition
      Error in `value[[3L]]()`:
      ! Error in connect()
      i Error in connect()

---

    Code
      print(s3)
    Output
      S3:
        tmproot: . 
        bucket: NULL 
        prefix: NULL 
        s3root: NULL 
        connected: FALSE 

---

    Code
      s3$connect()

---

    Code
      print(s3)
    Output
      S3:
        tmproot: . 
        bucket: NULL 
        prefix: NULL 
        s3root: NULL 
        connected: TRUE 

# S3 connect method works correctly

    Code
      s3$connect()
      print(s3)
    Output
      S3:
        tmproot: <temp_dir>
        bucket: my_bucket 
        prefix: data/ 
        s3root: NULL 
        connected: TRUE 

